version: "3.7"
services:
 php: 
  image: php:7.2-apache
  volumes: 
   - ./php:/var/www/html
  ports:
   - "8080:80"
  depends_on:
   - db

 db: 
  image: mysql:5.7
  volumes:
   - ./db:/var/lib/mysql/
  ports:
   - "3306:3306"
  restart: always
  platform: linux/x86_64
  environment:
   MYSQL_ROOT_PASSWORD: "password"
   MYSQL_DATABASE: "mysqldb"
   MYSQL_USER: "mysqluser"
   MYSQL_PASSWORD: "password"
